# -*- coding: utf-8 -*-
"""kripto-2enkripsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFDpLfAKd-czZcelifyxrfnwq-dV_ieI
"""

# pip install pycipher

import streamlit as st
from pycipher import Vigenere
from pycipher import Beaufort
st.title("KRIPTOGRAFI")
plain_text=st.text_input("Enter the message: ")
key=st.text_input("Enter the key: ")
vigenere_cipher = Vigenere (key).encipher(plain_text)
st.write("CIPHER TEXT VIGENERE CIPHER : ",vigenere_cipher)
a=st.text_input("Enter the key: ")
beaufort_cipher = Beaufort (a).encipher(vigenere_cipher)
st.write("CIPHER TEXT BEAUFORT CIPHER : ",beaufort_cipher)
d = Beaufort (a).decipher(beaufort_cipher)

# e = Vigenere (key).decipher(d)

print("---HASIL ENKRIPSI---")

st.write("PLAIN TEXT : ",d)

# print("---VIGENERE CIPHER---")
# print("CIPHER TEXT : ",vigenere_cipher)
